// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: app.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appByKey = `-- name: AppByKey :one
SELECT id, name, url, type, auth_ignore, auth_key, auth_secret, key
FROM public.app
WHERE key = $1
`

func (q *Queries) AppByKey(ctx context.Context, key pgtype.Text) (App, error) {
	row := q.db.QueryRow(ctx, appByKey, key)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.Type,
		&i.AuthIgnore,
		&i.AuthKey,
		&i.AuthSecret,
		&i.Key,
	)
	return i, err
}
