// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID         int64       `json:"id"`
	Name       pgtype.Text `json:"name"`
	Url        pgtype.Text `json:"url"`
	Type       pgtype.Text `json:"type"`
	AuthIgnore pgtype.Bool `json:"auth_ignore"`
	AuthKey    pgtype.Text `json:"auth_key"`
	AuthSecret pgtype.Text `json:"auth_secret"`
	Key        pgtype.Text `json:"key"`
}

type AppData struct {
	ID     pgtype.Int8 `json:"id"`
	Module pgtype.Text `json:"module"`
	Data   []byte      `json:"data"`
	AppID  pgtype.Int4 `json:"app_id"`
}

type User struct {
	ID       int64              `json:"id"`
	Phone    pgtype.Text        `json:"phone"`
	Email    pgtype.Text        `json:"email"`
	Nickname pgtype.Text        `json:"nickname"`
	Group    pgtype.Text        `json:"group"`
	Status   pgtype.Int4        `json:"status"`
	Created  pgtype.Timestamptz `json:"created"`
	Updated  pgtype.Timestamptz `json:"updated"`
	Aid      pgtype.Text        `json:"aid"`
	Secret   pgtype.Text        `json:"secret"`
}
