// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const userById = `-- name: UserById :one
SELECT id, phone, email, nickname, "group", status, created, updated, aid, secret
FROM public.user
WHERE id = $1
`

func (q *Queries) UserById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, userById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Group,
		&i.Status,
		&i.Created,
		&i.Updated,
		&i.Aid,
		&i.Secret,
	)
	return i, err
}

const userByPhone = `-- name: UserByPhone :one
SELECT id, phone, email, nickname, "group", status, created, updated, aid, secret
FROM public.user
WHERE phone = $1
`

func (q *Queries) UserByPhone(ctx context.Context, phone pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, userByPhone, phone)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Phone,
		&i.Email,
		&i.Nickname,
		&i.Group,
		&i.Status,
		&i.Created,
		&i.Updated,
		&i.Aid,
		&i.Secret,
	)
	return i, err
}
